package innowise.zuevsky.helpdesk.domain.enums;

public enum Category {
  APPLICATION_AND_SERVICES,
  BENEFITS_AND_PAPER_WORK,
  HARDWARE_AND_SOFTWARE,
  PEOPLE_MANAGEMENT,
  SECURITY_AND_ACCESS,
  WORKPLACES_AND_FACILITIES
}
